python lerobot/scripts/control_robot.py \
  --robot.type=koch \
  --control.type=record \
  --control.single_task="Grasp a bottle and put it in the box." \
  --control.fps=30 \
  --control.repo_id=${HF_USER}/koch_test2 \
  --control.tags='["tutorial"]' \
  --control.warmup_time_s=5 \
  --control.episode_time_s=30 \
  --control.reset_time_s=10 \
  --control.num_episodes=3 \
  --control.push_to_hub=true